model = "gpt-5.6-sol"
model_reasoning_effort = "high"

[projects."/home/ezekiel.flaton/devel/colcon_ws/src"]
trust_level = "trusted"

[features]
rmcp_client = true
terminal_resize_reflow = true
goals = true
js_repl = false

[notice]
fast_default_opt_out = true

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[plugins."slack@openai-curated"]
enabled = true

[plugins."atlassian-rovo@openai-curated"]
enabled = true

[plugins."box@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."google-calendar@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[tui.model_availability_nux]
"gpt-5.5" = 4

[marketplaces.openai-bundled]
last_updated = "2026-08-12T21:27:36Z"
source_type = "local"
source = "/home/ezekiel.flaton/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-08-12T21:28:14Z"
source_type = "local"
source = "/home/ezekiel.flaton/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[mcp_servers.node_repl]
args = []
command = "/usr/lib/chatgpt/resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/usr/lib/chatgpt/resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/usr/lib/chatgpt/resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/home/ezekiel.flaton/.codex:/usr/lib/chatgpt/resources/cua_node/lib/node_modules"
CODEX_HOME = "/home/ezekiel.flaton/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "e7fc907079d6797973cb63f97d2562c965aad8d33f52fb726005bf6702f30afc"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.803.81509"
CODEX_CLI_PATH = "/usr/lib/chatgpt/resources/codex"

[shell_environment_policy.set]
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "e7fc907079d6797973cb63f97d2562c965aad8d33f52fb726005bf6702f30afc"
NODE_REPL_TRUSTED_CODE_PATHS = "/home/ezekiel.flaton/.codex:/usr/lib/chatgpt/resources/cua_node/lib/node_modules"

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = false

#[mcp_servers.atlassian]
#command = "npx"
#args = ["-y", "mcp-remote", "https://mcp.atlassian.com/v1/mcp", "--transport", "http-only"]
#startup_timeout_sec = 30

